### ISSUE TITLE
 TypeError: this.channel.sendMenu is not a function

### ISSUE THREAD

**Issue by BubbletopTag** [Mundayne/reaction-menu#3]
My help command randomly stopped working and when type /help i get an error that says:
at Promise (/app/src/menu.js:18:22)
    at new Promise (<anonymous>)
at Menu.send (/app/src/menu.js:14:12)
at Client.client.on (/app/index.js:738:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-11-21T21:23:31.290Z] TypeError: this.channel.sendMenu is not a function
at Promise (/app/src/menu.js:18:22)
    at new Promise (<anonymous>)
at Menu.send (/app/src/menu.js:14:12)
at Client.client.on (/app/index.js:738:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
What should i do?

**Comment by Mundayne** [comment]
Can you paste the contents of your `package.json` file please?

**Comment by BubbletopTag** [comment]
It turns out the command just doesn't work in DMs

**Comment by Mundayne** [comment]
Whoops didn't mean to close...
I'll add the ability to send these messages in DM, when I first made this I didn't realise TextBasedChannel was different to TextChannel. Expect a fix some time this week.

**Comment by Mundayne** [comment]
This has been fixed in 2.1.0. Sorry for taking so long.
